pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/theobjectorientedguy/AI-Youtube-Summarizer'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                # Update package list and install Python and pip
                apt-get update
                apt-get install -y python3 python3-pip

                # Install project dependencies
                pip3 install --upgrade pip
                pip3 install -r ai-blog-article-generator/requirements.txt
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                python3 ai-blog-article-generator/manage.py makemigrations
                python3 ai-blog-article-generator/manage.py migrate
                '''
                echo 'Building the project...'
            }
        }

        stage('Run') {
            steps {
                sh '''
                python3 ai-blog-article-generator/manage.py runserver 0.0.0.0:5500
                '''
            }
        }
    }
}
